version: '3'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
